[package]
name = "ceiar"
version = "0.1.0"
authors = ["shockham <samuel.hockham@gmail.com>"]

[dependencies]
banana_rs = { git = "https://github.com/shockham/banana.git" }
temple = { git = "https://github.com/shockham/temple.git" }
kv_cab = { git = "https://github.com/shockham/kv_cab.git" }
